# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/backend" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "yarn" # See documentation for possible values
    directory: "/backend" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "kotlin-js-store" # See documentation for possible values
    directory: "/backend" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/app" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/feature/HomePage" # Location of package manifests
    schedule:
      interval: "daily"
      - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/platforms-intergation/Chillback" # Location of package manifests
    schedule:
      interval: "daily"
